# Generated by Django 4.2.4 on 2023-08-17 02:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('money_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(default='Hamptonroad area', max_length=100)),
                ('note', models.TextField(default='Would you like to put some notes for this transaction')),
            ],
        ),
    ]
